[package]
name = "s"
version = "1.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
confy = "1.0.0"
inquire = "0.7.5"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
